[Metadata]
Name=Gemini
Information=Variables for the Pollux (Gaming/Entertainment) sidebar.
Author=TruCola
Version=1.0

[Variables]
:x----- Color Scheme -----x:
red=0,0,28
teal=0, 255, 100
orange=255,0,100
blurple=25, 44, 191
blue=0, 136, 255
text=50,100,255
purple=120,0,255
pink=0,255,255

:x----- prvi panel, C & accent, CPU & play buttons, pc icon, RAM, speakers icon, D-----x:

:x----- Play Icons / Paths -----x:
App1=Spotify
App1Path=C:\Users\Home\AppData\Roaming\Spotify\Spotify.exe

App2=Discord
App2Path=C:\Users\Home\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Discord Inc\Discord.lnk

App3=Steam
App3Path=C:\Users\Home\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\steam.lnk

App4=VALORANT
App4Path=C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Riot Games\VALORANT.lnk
App4Image=#@#\Images\Pollux\valorant.jpg

App5=GRAND THEFT AUTO V
App5Path=steam://rungameid/271590
App5Image=#@#\Images\Pollux\gtav.jpg

App6=GENSHIN IMPACT
App6Path=com.epicgames.launcher://apps/879b0d8776ab46a59a129983ba78f0ce%3A7d690c122fde4c60bed85405f343ad10%3A41869934302e4b8cafac2d3c0e7c293d?action=launch&silent=true
App6Image=#@#\Images\Pollux\genshinimpact.jpg

App7=SIMS 4
App7Path=‪E:\Igrice\The Sims 4\TS4_x64 - Shortcut.lnk
App7Image=#@#\Images\Pollux\sims4.jpg

App8=BATMAN: AO
App8Path=steam://rungameid/209000
App8Image=#@#\Images\Pollux\bao.jpg

App9=MASS EFFECT
App9Path="E:\Igrice\Mass Effect Legendary Edition\Game\Launcher\MassEffectLauncher.exe"
App9Image=#@#\Images\Pollux\masseffect.jpg

App10=FALL GUYS
App10Path=com.epicgames.launcher://apps/50118b7f954e450f8823df1614b24e80%3A38ec4849ea4f4de6aa7b6fb0f2d278e1%3A0a2d9f6403244d12969e11da6713137b?action=launch&silent=true
App10Image=#@#\Images\Pollux\fallguys.jpg

App11=FORTNITE
App11Path=com.epicgames.launcher://apps/fn%3A4fe75bbc5a674f4f9b356b5c90567da5%3AFortnite?action=launch&silent=true		
App11Image=#@#\Images\Pollux\fortnite.jpg

App12=video-folder
App12Path="E:\Rezervna Kopija\Videos\GeForce Experience\Valorant"

App13=host
App13Path="%SystemRoot%\explorer.exe"

App14=recycle-bin
App14Path="C:\Users\Home\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Recycle Bin.lnk"

App15=stop1
App15Path="C:\Users\Home\AppData\Roaming\Microsoft\Windows\Start Menu\0valoKill.bat.lnk"

App16=chrome
App16Path="C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Incognito.lnk"

App17=Push2Run
App17Path="C:\Users\Home\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Push2Run.lnk"

App18=msiafterburner
App18Path="C:\Users\Home\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\MSI Afterburner\MSI Afterburner.lnk"

App19=hwmonitor
App19Path="C:\ProgramData\Microsoft\Windows\Start Menu\Programs\CPUID\HWMonitor\HWMonitor.lnk"

App20=flow
App20Path="C:\Users\Home\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps\Flow Launcher.lnk"

App21=synapse
App21Path="C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Razer\Razer Synapse.lnk"