[Metadata]
Name=Gemini
Author=TruCola
Version=1.0

[Variables]
font=Fira Code
font2=Anka/Coder Condensed
font3=Anka/Coder
player=web
location=06457
unit=i


:x----- Wallpapers -----x:
PolluxPath=#@#\Images\pollux.png
CastorPath=#@#\Images\castor.png


:x----- Icons -----x:
x=#@#\Icons\close.png


:x----- Color Scheme -----x:
white=255,255,255
black=0,0,0
lbackground=0,0,28
background=0, 255, 100
dbackground=0,255,255
shadow=255,0,200


:x----- Time of Day -----x:
TimeOfDay="00":"Good Night","01":"Good Night","02":"Good Night","03":"Good Night","04":"Good Night","05":"Good Night","06":"Good Night","07":"Good Morning","08":"Good Morning","09":"Good Morning","10":"Good Morning","11":"Good Morning","12":"Good Afternoon","13":"Good Afternoon","14":"Good Afternoon","15":"Good Afternoon","16":"Good Afternoon","17":"Good Afternoon","18":"Good Evening","19":"Good Evening","20":"Good Evening","21":"Good Evening","22":"Good Evening","23":"Good Evening"