[Variables]

; --- PROGRESS BAR
orientation_progressbar=Vertical
width_progressbar=1.75
height_progressbar=102
;^87.5
xpos_progressbar=108
;^77
ypos_progressbar=4
;10.5

; --- NOW
xpos_now=70
ypos_now=38.5

; --- PLAYING
xpos_playing=70
ypos_playing=50.75

; --- NOW PLAYING FOR CENTER
xpos_nowplaying=241.5
ypos_nowplaying=15.75

; --- UPDATE INDICATOR
xpos_indicator=24.5
ypos_indicator=41.125

; --- TIME
xpos_time=112
;^70
ypos_time=10
;^12.25

; --- PROGRESS
xpos_progress=112
;^70
ypos_progress=82
;^22.75

; --- SETTINGS
xpos_settings=43.75
ypos_settings=22.75

; --- PLAY BUTTON
xpos_play=42
ypos_play=82.25

; --- PREVIOUS BUTTON
xpos_prev=70
ypos_prev=70

; --- NEXT BUTTON
xpos_next=70
ypos_next=82.25

; --- INTERFACE
align_interface=Left

; --- REGULAR: CONTAINERS
xpos_container_reg=85.75
ypos_containertop_reg=19.25
ypos_containerbtm_reg=49.875
width_container_reg=380.625

; --- STANDARD: CONTAINERS
width_container_std=380.625
width_container_scroll=346
;448^
height_container_std=38.5

; --- CONTAINER TEXT
xpos_containertext=0
ypos_containertextbtm=0
ypos_containertexttop=42
align_containertext_supposed=Left

; PURE --------------

; --- PURE, UPDATE INDICATOR
pure_xpos_indicator=0

; --- PURE, REGULAR: CONTAINERS
pure_ypos_containertop_reg=15.75
pure_ypos_containerbtm_reg=46.375
