[MeterBar0]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed0]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar1]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed1]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar2]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed2]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar3]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed3]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar4]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed4]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar5]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed5]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar6]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed6]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar7]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed7]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar8]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed8]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar9]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed9]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar10]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed10]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar11]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed11]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar12]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed12]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar13]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed13]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar14]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed14]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar15]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed15]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar16]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed16]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar17]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed17]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar18]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed18]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar19]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed19]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar20]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed20]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar21]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed21]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar22]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed22]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar23]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed23]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar24]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed24]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar25]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed25]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar26]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed26]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar27]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed27]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar28]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed28]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar29]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed29]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar30]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed30]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar31]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed31]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar32]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed32]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar33]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed33]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar34]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed34]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar35]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed35]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar36]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed36]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar37]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed37]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar38]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed38]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar39]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed39]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar40]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed40]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar41]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed41]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar42]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed42]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar43]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed43]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar44]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed44]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar45]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed45]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar46]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed46]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar47]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed47]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar48]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed48]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar49]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed49]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar50]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed50]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar51]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed51]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar52]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed52]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar53]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed53]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar54]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed54]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar55]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed55]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar56]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed56]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar57]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed57]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar58]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed58]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar59]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed59]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar60]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed60]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar61]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed61]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar62]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed62]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar63]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed63]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar64]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed64]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar65]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed65]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar66]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed66]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar67]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed67]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar68]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed68]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar69]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed69]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar70]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed70]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar71]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed71]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar72]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed72]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar73]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed73]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar74]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed74]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar75]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed75]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar76]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed76]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar77]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed77]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar78]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed78]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar79]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed79]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar80]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed80]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar81]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed81]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar82]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed82]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar83]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed83]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar84]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed84]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar85]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed85]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar86]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed86]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar87]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed87]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar88]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed88]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar89]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed89]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar90]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed90]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar91]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed91]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar92]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed92]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar93]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed93]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar94]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed94]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar95]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed95]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar96]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed96]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar97]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed97]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar98]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed98]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar99]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=1R
Y=350
Shape=Rectangle 0,0,(7*0.8),(-(350-(7*0.8))*[MeasureAudioSmoothed99]-(7*0.8)),((7*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1